version: '3'
services:
  nginx:
    build: ./nginx
    image: brecheisen/PROJECTNAME-nginx:latest
    container_name: PROJECTNAME_nginx
    ports:
      - "8002:8000"
    volumes:
      - data:/data
    depends_on:
      - web
  web:
    build: .
    image: brecheisen/PROJECTNAME-web:latest
    container_name: PROJECTNAME_web
    environment:
      - SECRET_KEY
    volumes:
      - ./src/PROJECTNAME:/src
      - data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on:
      - db
  redis:
    restart: always
    image: redis:6.2.5
    container_name: PROJECTNAME_redis
    command: bash -c "redis-server"
    ports:
      - "6379:6379"
  rq:
    image: brecheisen/PROJECTNAME-web:latest
    container_name: PROJECTNAME_rq
    command: bash -c "python manage.py rqworker"
    environment:
      - SECRET_KEY
    volumes:
      - ./src/PROJECTNAME:/src
      - data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: postgres:10.5-alpine
    container_name: PROJECTNAME_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/localscratch/docker/PROJECTNAME/data
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/localscratch/docker/PROJECTNAME/postgres_data
